// Fetch all the articles.
export const FETCH_ARTICLES_REQUESTED = 'FETCH_ARTICLES_REQUESTED'
export const FETCH_ARTICLES_SUCCEEDED = 'FETCH_ARTICLES_SUCCEEDED'
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED'

// Create a new article.
export const CREATE_ARTICLE_REQUESTED = 'CREATE_ARTICLE_REQUESTED'
export const CREATE_ARTICLE_SUCCEEDED = 'CREATE_ARTICLE_SUCCEEDED'
export const CREATE_ARTICLE_FAILED = 'CREATE_ARTICLE_FAILED'

// Fetch a specific article.
export const FETCH_ARTICLE_REQUESTED = 'FETCH_ARTICLE_REQUESTED'
export const FETCH_ARTICLE_SUCCEEDED = 'FETCH_ARTICLE_SUCCEEDED'
export const FETCH_ARTICLE_FAILED = 'FETCH_ARTICLE_FAILED'
